### ISSUE TITLE
Passing zero as occurence number

### ISSUE THREAD

**Issue by lemingos** [gampleman/icui#3]
I think it would be better to block possibility of passing 0 to "every" input

https://github.com/gampleman/icui/blob/master/lib/icui.coffee#L368

min option should do the trick:

```
<input type="number" value="#{@data.interval}" size="2" width="30" min="1" /> 
```

Passing 0 resuts with error: '0' is not a valid input for interval. Please pass an integer.

**Comment by gampleman** [comment]
Sounds like a good idea.
